<?php

namespace common\models\materials\attribute;

use common\components\Common;
use Yii;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "attribute_group".
 *
 * @property int $id
 * @property string $title
 * @property string $sort
 * @property int $status
 * @property ActiveQuery attribute_list
 */
class AttributeGroup extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'attribute_group';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['sort', 'status'], 'integer'],
            [['sort'], 'default', 'value' => 0],
            [['status'], 'default', 'value' => 1],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название группы атрибутов',
            'sort' => 'Порядок сортировки',
            'status' => 'Status',
        ];
    }

    public static function getTitle($id) {
        $title = self::findOne($id)->title;
        return $title ? $title : false;
    }

    public function getAttribute_list()
    {
        return $this->hasMany(Attribute::className(), ['group_id' => 'id']);
    }

    /**
     * @return bool
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function beforeDelete()
    {
        Common::deleteAll($this->attribute_list);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
