<?php

namespace backend\widgets;


use yii\base\Widget;
use yii\helpers\Html;

class FormWidget extends Widget
{
    public $copyable;

    public function run()
    {
        echo '<div class="form-group multiple-buttons">';
        echo Html::submitButton('Сохранить', ['name' => 'save', 'class' => 'btn btn-success']);
        echo Html::submitButton('Сохранить и закрыть', ['name' => 'save-close', 'class' => 'btn btn-primary']);
        echo Html::submitButton('Сохранить и создать', ['name' => 'save-create', 'class' => 'btn btn-primary']);
        if ($this->copyable)
            echo Html::submitButton('Сохранить и копировать', ['name' => 'save-copy', 'class' => 'btn btn-primary']);
        echo Html::a('<i class="fa fa-close"></i>', ['index'], [
            'class' => 'btn btn-danger',
            'title' => 'Выход',
        ]);
        echo '</div>';
        parent::run(); // TODO: Change the autogenerated stub
    }
}